test_date_strs = [
    "2014",
    "2014-02",
    "2014/08/12",
    "08/12",
    "2014-08-12.12",
    "this_year",
    "this_month",
    "this_week",
    "this_day",
    "this_hour",
    "last_year",
    "last_month",
    "last_week",
    "last_day",
    "last_hour",
    "1 year",
    "2 months",
    "3 weeks",
    "4 days",
    "5 hours",
    # "past year",
    # "past.month",
    # "past-week",
    # "过去一天",
    # "past_hour",
]
