services:
  bili-seach-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: bff1209
    image: bili-search
    network_mode: host
    volumes:
      - ./configs/secrets.json:/app/configs/secrets.json
      - ./configs/elastic_ca.crt:/app/configs/elastic_ca.crt
# docker compose up --build
