services:
  bili-seach-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: 04f510f
    image: bili-search:0.1
    ports:
      - "21001:21001"
    volumes:
      - ./configs:/app/configs
# docker compose up
