services:
  bili-seach-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_MIRROR: http://mirrors.tuna.tsinghua.edu.cn/ubuntu/
        PIP_MIRROR: https://pypi.tuna.tsinghua.edu.cn/simple
        COMMIT_HASH: ae11c23
    image: bili-search
    network_mode: host
    volumes:
      - ./configs:/app/configs
# docker compose up --build
